//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace sample_wssf.DataContracts
{
	/// <summary>
	/// Data Contract Class - ListDCEmployee
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://puentesarr.in", ItemName = "ListDCEmployee")]
	public partial class ListDCEmployee : System.Collections.Generic.List<DCEmployee>
	{
	}
}

