//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_wssf.WebClient.ProxyServiceEmployee {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListDCEmployee", Namespace="http://puentesarr.in", ItemName="ListDCEmployee")]
    [System.SerializableAttribute()]
    public class ListDCEmployee : System.Collections.Generic.List<sample_wssf.WebClient.ProxyServiceEmployee.DCEmployee> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCEmployee", Namespace="http://puentesarr.in")]
    [System.SerializableAttribute()]
    public partial class DCEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://puentesarr.in", ConfigurationName="ProxyServiceEmployee.ServiceContractEmployee")]
    public interface ServiceContractEmployee {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SelectAllEmployees no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="SelectAllEmployees", ReplyAction="http://puentesarr.in/ServiceContractEmployee/SelectAllEmployeesResponse")]
        sample_wssf.WebClient.ProxyServiceEmployee.selectAllEmployeesResponse SelectAllEmployees(sample_wssf.WebClient.ProxyServiceEmployee.SelectAllEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllEmployeesRequest {
        
        public SelectAllEmployeesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://puentesarr.in", Order=0)]
        public sample_wssf.WebClient.ProxyServiceEmployee.ListDCEmployee ListEmployees;
        
        public selectAllEmployeesResponse() {
        }
        
        public selectAllEmployeesResponse(sample_wssf.WebClient.ProxyServiceEmployee.ListDCEmployee ListEmployees) {
            this.ListEmployees = ListEmployees;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceContractEmployeeChannel : sample_wssf.WebClient.ProxyServiceEmployee.ServiceContractEmployee, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceContractEmployeeClient : System.ServiceModel.ClientBase<sample_wssf.WebClient.ProxyServiceEmployee.ServiceContractEmployee>, sample_wssf.WebClient.ProxyServiceEmployee.ServiceContractEmployee {
        
        public ServiceContractEmployeeClient() {
        }
        
        public ServiceContractEmployeeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceContractEmployeeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractEmployeeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractEmployeeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sample_wssf.WebClient.ProxyServiceEmployee.selectAllEmployeesResponse sample_wssf.WebClient.ProxyServiceEmployee.ServiceContractEmployee.SelectAllEmployees(sample_wssf.WebClient.ProxyServiceEmployee.SelectAllEmployeesRequest request) {
            return base.Channel.SelectAllEmployees(request);
        }
        
        public sample_wssf.WebClient.ProxyServiceEmployee.ListDCEmployee SelectAllEmployees() {
            sample_wssf.WebClient.ProxyServiceEmployee.SelectAllEmployeesRequest inValue = new sample_wssf.WebClient.ProxyServiceEmployee.SelectAllEmployeesRequest();
            sample_wssf.WebClient.ProxyServiceEmployee.selectAllEmployeesResponse retVal = ((sample_wssf.WebClient.ProxyServiceEmployee.ServiceContractEmployee)(this)).SelectAllEmployees(inValue);
            return retVal.ListEmployees;
        }
    }
}
