//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace sample_wssf.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - ServiceContractEmployee
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://puentesarr.in", Name = "ServiceContractEmployee", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IServiceContractEmployee 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "SelectAllEmployees", ProtectionLevel = ProtectionLevel.None)]
		sample_wssf.MessageContracts.selectAllEmployeesResponse SelectAllEmployees();

	}
}

