//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace sample_wssf.MessageContracts
{
	/// <summary>
	/// Service Contract Class - selectAllEmployeesResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class selectAllEmployeesResponse
	{
		private sample_wssf.DataContracts.ListDCEmployee listEmployees;
	 		
		[WCF::MessageBodyMember(Name = "ListEmployees")] 
		public sample_wssf.DataContracts.ListDCEmployee ListEmployees
		{
			get { return listEmployees; }
			set { listEmployees = value; }
		}
	}
}

